version: '3'

services:
    nginx:
        image: nginx:latest
        container_name: project_nginx
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        container_name: project_app
        volumes:
            - ./:/var/www/
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: project_db
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: lardocker
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8101:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
#        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password

